# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1444015083);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1444015203);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1444011999);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1444014963);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1444008279);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 296960);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150114162216");
user_pref("browser.slowStartup.averageTime", 3733);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150114162216");
user_pref("browser.startup.homepage_override.mstone", "31.4.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1444014612666");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1444014613650");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1444101013650");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1444004622204");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1444005883985");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-button-pressed");
user_pref("datareporting.policy.firstRunTime", "1443928203468");
user_pref("datareporting.sessions.current.activeTicks", 667);
user_pref("datareporting.sessions.current.firstPaint", 3299);
user_pref("datareporting.sessions.current.main", 1125);
user_pref("datareporting.sessions.current.sessionRestored", 3526);
user_pref("datareporting.sessions.current.startTime", "1444004556564");
user_pref("datareporting.sessions.current.totalTime", 10621);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1443925463000,\"rdfTime\":1421253544000}}}]");
user_pref("extensions.lastAppVersion", "31.4.0");
user_pref("extensions.lastPlatformVersion", "31.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20150114162216");
user_pref("gecko.mstone", "31.4.0");
user_pref("idle.lastDailyNotification", 1444015358);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1444014612);
user_pref("places.history.expiration.transient_current_max_pages", 30957);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1443928958);
user_pref("toolkit.startup.last_success", 1444004557);
user_pref("toolkit.telemetry.previousBuildID", "20150114162216");
